### ISSUE TITLE
Instructions please!

### ISSUE THREAD

**Issue by dpedrinha** [postworthy/OrderByNatural#1]
Ok, the name of the plugin is very promising, but it would be really nice to have some quick instructions and an example of how "natural" it is.
Thanks

**Comment by postworthy** [comment]
first you will need to have the project properly linked in your solution and you will need to add a using statement for the namespace: com.LandonKey.OrderByNatural

ex:

using com.LandonKey.OrderByNatural;

Once you have the namespace referenced then you will see a new extension method available for any Enumeral<T>

Here is the extension method code:
https://github.com/postworthy/OrderByNatural/blob/master/OrderByNatural/OrderByNaturalExtensions.cs

and here is an example of using it:

var my_list = new List<string>{ "1. one", "4. Four", "3. Three", "2. Two", "10. Ten"};
my_list.OrderByNatural(x=>x).Foreach(x=>{ Console.WriteLine(x); });

The orderby natural will order the numeric values as you would expect highest to lowest number and not by ascii ordering which would be the normal way an orderby would work on a string.

OrderByNatural can work on any type of object c9ollection so long as you use the function you pass to it to resurn a property of type string.

**Comment by dpedrinha** [comment]
Thank you very much!
